# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BsN23tLhwenOgAXkQnm_WcLYyVzejNY7
"""

!pip install gtts

from gtts import gTTS
import os
text="""Ты — свет моей души, моя весна,
Когда вокруг метель и тишина.
С тобой теплее даже в холода,
Ты — мой огонь, что гаснуть никогда не будет.
"""
language="ru"
tts=gTTS(text=text,lang=language,slow=True)
audio_file="pushking_sheri.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio (audio_file)

from gtts import gTTS
import os
text="""Allons enfants de la Patrie,
Le jour de gloire est arrivé !
Contre nous de la tyrannie
L'étendard sanglant est levé, (bis)
Entendez-vous dans les campagnes
Mugir ces féroces soldats ?
Ils viennent jusque dans vos bras
Égorger vos fils, vos compagnes !

Aux armes, citoyens,
Formez vos bataillons,
Marchons, marchons !
Qu’un sang impur
Abreuve nos sillons !

Que veut cette horde d’esclaves,
De traîtres, de rois conjurés ?
Pour qui ces ignobles entraves,
Ces fers dès longtemps préparés ? (bis)
Français, pour nous, ah! quel outrage
Quels transports il doit exciter !
C’est nous qu’on ose méditer
De rendre à l’antique esclavage !

Aux armes, citoyens…

Quoi ! des cohortes étrangères
Feraient la loi dans nos foyers !
Quoi ! Ces phalanges mercenaires
Terrasseraient nos fiers guerriers ! (bis)
Grand Dieu! Par des mains enchaînées
Nos fronts sous le joug se ploieraient
De vils despotes deviendraient
Les maîtres de nos destinées !

Aux armes, citoyens…

Tremblez, tyrans et vous perfides
L’opprobre de tous les partis,
Tremblez ! vos projets parricides
Vont enfin recevoir leurs prix ! (bis)
Tout est soldat pour vous combattre,
S’ils tombent, nos jeunes héros,
La terre en produit de nouveaux,
Contre vous tout prêts à se battre !

Aux armes, citoyens…

Français, en guerriers magnanimes,
Portez ou retenez vos coups !
Épargez ces tristes victimes,
À regret s’armant contre nous. (bis)
Mais ces despotes sanguinaires,
Mais ces complices de Bouillé,
Tous ces tigres qui, sans pitié,
Déchirent le sein de leur mère !

Aux armes, citoyens…

Amour sacré de la Patrie,
Conduis, soutiens nos bras vengeurs
Liberté, Liberté chérie,
Combats avec tes défenseurs ! (bis)
Sous nos drapeaux que la victoire
Accoure à tes mâles accents,
Que tes ennemis expirants
Voient ton triomphe et notre gloire !

Aux armes, citoyens…

(Couplet des enfants)
Nous entrerons dans la carrière
Quand nos aînés nʼy seront plus,
Nous y trouverons leur poussière
Et la trace de leurs vertus (bis)
Bien moins jaloux de leur survivre
Que de partager leur cercueil,
Nous aurons le sublime orgueil
De les venger ou de les suivre. """
language="fr"
tts=gTTS(text=text,lang=language,slow=False)
audio_file="fransuz_madhiyasi.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio (audio_file)

from gtts import gTTS
import os
text="""I have several daily habits that help me stay organized and healthy. Every morning I wake up early and make my bed. Then I wash my face, brush my teeth, and eat a light breakfast. I also like to read for a few minutes before starting my day. After school, I usually do my homework and help my family with small chores. In the evening, I try to spend some time exercising or walking outside. Before going to sleep, I plan my tasks for the next day. These habits keep me disciplined and make my life easier and more productive.

"""
language="en"
tts=gTTS(text=text,lang=language,slow=False)
audio_file="atim_odatlari.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio (audio_file)

from gtts import gTTS
import os
text="您好"
language="zh-CN"
tts=gTTS(text=text,lang=language,slow=False)
audio_file="hitoycha_salom.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio (audio_file)

from gtts import gTTS
import os
text=" assalom alekukum talabalar   "
language="tr"
tts=gTTS(text=text,lang=language,slow=False)
audio_file="aytilgan_file.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio (audio_file)